import Head from "next/head";
import Header from "../components/shared/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Baby Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
      </div>
    </>
  );
}
